name: Add Community PRs to Project
on:
  schedule:
  # cron schedule expression to run at 5 minutes past every hour 
    - cron: "5 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Handle vocabulary Repo
      uses: subhamX/github-project-bot@v1.0.0
      with:
        ACCESS_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
        COLUMN_NAME: "In Progress"
        PROJECT_URL: https://github.com/orgs/creativecommons/projects/13
        REPO_URL: https://github.com/creativecommons/vocabulary
    - name: Handle vue-vocabulary Repo
      uses: subhamX/github-project-bot@v1.0.0
      with:
        ACCESS_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
        COLUMN_NAME: "In Progress"
        PROJECT_URL: https://github.com/orgs/creativecommons/projects/13
        REPO_URL: https://github.com/creativecommons/vue-vocabulary
    - name: Handle fonts Repo
      uses: subhamX/github-project-bot@v1.0.0
      with:
        ACCESS_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
        COLUMN_NAME: "In Progress"
        PROJECT_URL: https://github.com/orgs/creativecommons/projects/13
        REPO_URL: https://github.com/creativecommons/fonts
